name: Publish Static Web App to Azure Blob Storage

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --auth-mode key -d '$web' -s $GITHUB_WORKSPACE/website
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlinescript: |
          az cdn endpoint purge -g ${{ secrets.RESOURCE_GROUP_NAME }} -n ${{ secrets.ENDPOINT_NAME }} --profile-name ${{ secrets.PROFILE_NAME }} --content-paths '/*'

# Azure logout
    - name: logout
      run: |
            az logout
      if: always()
